### ISSUE TITLE
How to override innerclasses or add Styling in innercomponents.

### ISSUE THREAD

**Issue by Uttu316** [grubersjoe/react-github-calendar#10]
I have no clue, how to override inner classes or add Styling in inner components?
for example:

- If I want to style the username.
- Hide the number of contributions for last year.
- the calendar should take width of 100% to its parent container.
- The username link should take me to another window, not on the same window.
- Loading... text can be changed with any other progress bar.

**Comment by grubersjoe** [comment]
* the title bar with the username is no longer shown (so simply add your own JSX code before the graph)
* contributions can be hidden by setting `showTotalCount` to `false` now
* if you want the SVG to take 100% of parent container width simply add `.react-github-calendar__calendar { width: 100%; }` to your CSS file
* obsolete now
* I plan to make the loading state more flexible through a render prop so users can do whatever the want to handle loading

**Comment by grubersjoe** [comment]
Closing since above comment should answer your questions. Feel free to reopen if necessary.
