### ISSUE TITLE
[Question] adjusting the calendar in mobile

### ISSUE THREAD

**Issue by 1chooo** [grubersjoe/react-github-calendar#102]
I am currently using this package, and I have successfully displayed it on my webpage. However, when loading in mobile mode, the slider is on the far left, and I want it to be displayed from the far right at the beginning. How can I make it?

Or I can switch the different GitHub stats between PC and mobile mode, mobile will auto render the smaller calendar. 

### Current

![image](https://github.com/user-attachments/assets/78ea530d-a9c5-4447-b4eb-637883b4fc82)

### Expected 
![image](https://github.com/user-attachments/assets/1e5fe3de-9696-42bf-a5e8-a948a03b47cc)

Thanks

**Comment by grubersjoe** [comment]
Hey. I think you have several possibilities:

### Using media queries and `transformData`

You could add something like [`react-responsive`](https://github.com/yocontra/react-responsive) to query the viewport width in React and dynamically reduce the amount of data you show using the `transformData` prop:

https://codesandbox.io/p/devbox/react-github-calendar-scroll-3cx8y9

### Scroll to the end using `scrollLeft`

Or if you really want to scroll the container you can set the [`scrollLeft`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollLeft) property of the HTML element using a [React ref](https://react.dev/learn/manipulating-the-dom-with-refs):

https://codesandbox.io/p/devbox/react-github-calendar-scroll-3cx8y9

**Comment by grubersjoe** [comment]
@1chooo I realized there was a bug in the `scrollLeft` approach, it did not scroll on the initial page load. I've updated the Codesandbox above that fixes that.

**Comment by 1chooo** [comment]
> @1chooo I realized there was a bug in the `scrollLeft` approach, it did not scroll on the initial page load. I've updated the Codesandbox above to fix that.

Thank you!
