### ISSUE TITLE
TypeError: chroma__default.default.scale is not a function

### ISSUE THREAD

**Issue by winnllam** [grubersjoe/react-github-calendar#105]
I installed the package but when trying to run my application I run into the following error

```
import GitHubCalendar from "react-github-calendar";
...
<GitHubCalendar username="winnllam" />
```

![image](https://github.com/user-attachments/assets/be76f28b-1de5-4847-8262-ed416de77012)

I have tried installing `chroma-js` as well but it did not fix the issue. My application is also using tailwind.css, not sure if that impacts this.

Please advise, thank you!

**Comment by grubersjoe** [comment]
Hey. What environment are you using (Next.js, Remix, Vite, Create React App etc.)?

Tried the current version in Vite using `npm create vite` and it renders just fine:

<img width="908" alt="image" src="https://github.com/user-attachments/assets/730b21e3-7ef0-4342-be4c-f08b7f3a20b8">

Tailwind should not play a role. Another thing you can try:

```bash
rm -rf node_modules/
npm install
```

**Comment by winnllam** [comment]
Hey! I'm using Create React App. This is how my dependencies and their versions look like.

![image](https://github.com/user-attachments/assets/85f902ec-f38a-4507-89bf-91e98a48c38d)

Ran the removal and `npm install` again but still having the same issue.

**Comment by grubersjoe** [comment]
Ah I remember now, it did sound familiar. This is an issue with CRA and there's not much this project can do, see here:

https://github.com/grubersjoe/react-activity-calendar/issues/105

**Comment by winnllam** [comment]
Managed to get it working with the workaround you linked, thanks for the help!
