### ISSUE TITLE
Data not matching up from GitHub

### ISSUE THREAD

**Issue by josiahroa18** [grubersjoe/react-github-calendar#11]
It appears that some commits are not appearing on the git hub calendar that I have implemented in my React app.

The contribution count also doesn't match. Not sure if this is an isolated issue.

Original GitHub Calendar
<img width="934" alt="GitHub" src="https://user-images.githubusercontent.com/35950476/75298059-b3e23200-57ee-11ea-8026-c91076a26783.png">

Component GitHub Calendar
<img width="759" alt="GitHubCalendar" src="https://user-images.githubusercontent.com/35950476/75298073-bfcdf400-57ee-11ea-95b4-727a9f34ad97.png">

**Comment by grubersjoe** [comment]
Please checkout the most recent version (`1.0.6`). Looks correct to me here. The total contributions count is off by one, but that's no big deal I guess.

![grafik](https://user-images.githubusercontent.com/3109364/85898740-1bd87180-b7fd-11ea-80ac-0016c4b5308a.png)
![grafik](https://user-images.githubusercontent.com/3109364/85898769-2b57ba80-b7fd-11ea-8877-5c23d39ded36.png)

**Comment by elihuansen** [comment]
I believe contributions to private repositories are not counted.
To have them counted, 
1. Go to https://github.com/settings/profile
2. Scroll to the **Contributions** section 
3. Enable **Include private contributions on my profile**
