### ISSUE TITLE
Does not work with Astro

### ISSUE THREAD

**Issue by sharunkumar** [grubersjoe/react-github-calendar#122]
![image](https://github.com/user-attachments/assets/a7742917-207b-4d8b-9c87-3500cf738d02)

Error:

```
TypeError
An error occurred.
Cannot read properties of undefined (reading 'toString')
```

Repository for reproduction:

https://gitlab.com/sharunkumar/astro-react-github-calendar

**Comment by grubersjoe** [comment]
I think the issue is that you're trying to render the calendar server-side. This is not supported. I've added a section to the README now. More details in the [known issues](https://github.com/grubersjoe/react-activity-calendar/blob/main/README.md#server-side-rendering).

Basically you have to use the `client:only` directive:
https://docs.astro.build/de/reference/directives-reference/#clientonly

**Comment by sharunkumar** [comment]
> Basically you have to use the `client:only` directive:

I tried adding `client:only` directive but it seems like it doesn't show up at all: https://gitlab.com/sharunkumar/astro-react-github-calendar/-/commit/1e0ff98633cd1efaa56a1df2b0e0a0ff0fe755c4

![image](https://github.com/user-attachments/assets/783b64f1-f011-4af2-b002-63b0b6c5b2d2)

**Comment by sharunkumar** [comment]
Note: adding `client-only` makes the component show up in the built version, but not when running astro dev mode

**Comment by grubersjoe** [comment]
Hey. Also took me a while to figure this out, but it's stated quite clearly in the [Astro documentation](https://docs.astro.build/en/basics/astro-components/) that

> The most important thing to know about Astro components is that they don’t render on the client. They render to HTML either at build-time or on-demand using [server-side rendering (SSR)](https://docs.astro.build/en/guides/server-side-rendering/).

So I'd say it is expected that if you use `react-activity-calendar` inside an `.astro` file it will only work after building the page. However, you can create a React component, render the calendar there and then include this component in your `.astro` file (using the `client:only="react"` directive).

See here a [working example](https://github.com/grubersjoe/react-activity-calendar-tests/blob/main/frameworks/astro/src/pages/index.astro).

**Comment by sharunkumar** [comment]
Got it, looks like introducing an "intermediate" Component solved it, based on your example: 

https://gitlab.com/sharunkumar/astro-react-github-calendar/-/merge_requests/1/diffs
