### ISSUE TITLE
Could not upgrade to React v19

### ISSUE THREAD

**Issue by 1chooo** [grubersjoe/react-github-calendar#149]
We are unable to upgrade to React v19 because of a dependency issue with `react-github-calendar`. The error message is as follows:

```bash
Could not resolve dependency:
npm ERR! peer react@"^17.0.0 || ^18.0.0" from react-github-calendar@4.5.1
npm ERR! node_modules/react-github-calendar
```

**Comment by grubersjoe** [comment]
Hey. I've just merged React 19 support. Please try again, should work now!

**Comment by 1chooo** [comment]
> Hey. I've just merged React 19 support. Please try again with version `v4.5.2`, should work now!

Thanks, @grubersjoe. Due to other priorities, I'll give it a try later.
