### ISSUE TITLE
Component not working after Github Updated their website

### ISSUE THREAD

**Issue by arunabharjun** [grubersjoe/react-github-calendar#18]
The graph does get the data but the colours remain blank. 
![Screenshot 2020-06-26 at 10 50 37 PM](https://user-images.githubusercontent.com/29682259/85883962-77a3fa00-b7ff-11ea-94fd-a76459a9e25f.png)

**Comment by grubersjoe** [comment]
Hey, thanks for pointing this out. I guess I have to adapt the scraping code then. Will look into that :+1:

**Comment by arunabharjun** [comment]
Most welcome. I really love this particular project. Makes my website look really great. Its the best component vote there to achieve what it does. Hope it gets back to working soon. 
Really appreciate your work.

**Comment by grubersjoe** [comment]
Glad you like it :)!

Okay, it should work again with latest package, now. GitHub changed their color palette and consequently the color intensity could no longer be determined since this is a simple `color => intensity` mapping.

Does it work for you?

**Comment by arunabharjun** [comment]
Yup! It perfectly does. Looks to great.
And really appropriate your prompt response.
Thank you so much.
