### ISSUE TITLE
Fail to get contributions

### ISSUE THREAD

**Issue by ihsuy** [grubersjoe/react-github-calendar#25]
Hey, I really liked your github-calendar component and have been using it on my website.
However, there seems to be an issue with contribution data retrieval and the calendar is blank now. 

After a little bit investigation in your code, I found this API_URL ('https://github-calendar.now.sh/v1/') that you are using has stopped returning contribution data.

Meantime, I found this API returns the correct contribution data: 
https://github.com/KaDw/github-calendar-api

Is there any hope we could fix this? I can't wait to have your Github-calendar displayed on my website again.
Thanks

**Comment by grubersjoe** [comment]
Hey. Unfortunately, this is not the first time the API stopped working because it simply scrapes the GitHub user profile. Whenever GitHub changes their HTML it might break. I'm going to fix this asap.

**Comment by grubersjoe** [comment]
Small update: I've fixed the API (not deployed yet, however). Since the API has changed a bit (new major version) I will need to also adapt the code here, which I will do tomorrow.

**Comment by arunabharjun** [comment]
Hi, Facing the same issue with my website. Your component is kind of the highlight of my website. Really looking foreward to the fix. Kudos to your work. It's awesome.
Thanks 😁

**Comment by grubersjoe** [comment]
Hey there. I released the fixed version `2.0.2`. It should work as before now. Please let me know if you still face issues. The new API is also able to scrape only specific years instead of scraping all available data as before. So in future API performance will also improve.

**Comment by ihsuy** [comment]
Hey, that's awesome!
I will be testing the new version and close the issue soon.
Thank you a lot for your work!!

**Comment by arunabharjun** [comment]
That's great news. Tested it and it works just fine. Thanks a lot for your work! 🤘🏼
