### ISSUE TITLE
Ability to reuse component for non-github use cases

### ISSUE THREAD

**Issue by blaenk** [grubersjoe/react-github-calendar#27]
This seems like a nice component!

I think it'd be great if one could use its main functionality (calendar heatmap) for other non-GitHub uses by allowing one to pass in some `values` prop, circumventing any GitHub API calls.

Here are other components that allow this, but they don't seem as active:

* https://github.com/haripo/react-github-contribution-calendar
* https://github.com/kevinsqi/react-calendar-heatmap

**Comment by grubersjoe** [comment]
Hey,

yes, this is a good idea and am already planning to do this. Right now this component is tightly coupled with the contributions [API](https://github.com/grubersjoe/github-contributions-api) and the usecase of showing a GitHub calendar. There is not really a good reason for this except maybe ease of use and lack of better planning 😄.

I'm going to extract the calendar into an unopinionated component that will draw a heatmap of whatever data it receives. This project would then be only a thin wrapper around this agnostic calendar component and the calendar itself could be used for other things. I've been working on the GitHub contributions API lately and these steps will be done next 👍🏽.

**Comment by blaenk** [comment]
That's great to hear! Thank you for responding.

**Comment by grubersjoe** [comment]
Here you go :). This project will also use below component in the next major release. 

https://github.com/grubersjoe/react-activity-calendar
https://grubersjoe.github.io/react-activity-calendar/?path=/story/activity-calendar--default

**Comment by blaenk** [comment]
Wow that's amazing! Thank you so much Jonathan!
