### ISSUE TITLE
color option seems not working

### ISSUE THREAD

**Issue by Newgin-sam** [grubersjoe/react-github-calendar#29]
I was trying color option and the color stays at green even when i give some other color

**code :**
` <GitHubCalendar username="newgin-sam" blockSize={20}
     blockMargin={5}
     color="#990f0f"
     fontSize={15}
 />`

**version**

> "react-github-calendar": "^3.0.3"

**issued output**

![image](https://user-images.githubusercontent.com/60768808/130488796-b681b112-90c9-413a-ba61-7be6b42df086.png)

**Comment by grubersjoe** [comment]
Hey. Sorry, the `color` property was in fact always overwritten with the default theme. Fixed in `v3.0.4`. Can you check if it's working as expected now?

**Comment by Newgin-sam** [comment]
Hi joe,
After updating to `v3.0.4` am getting error in the console as below.

Tried 

`npm uninstall react-github-calendar`

and 

`npm i react-github-calendar@3.0.4`

**ERROR :**
>./node_modules/react-github-calendar/dist/index.es.js 56:57
Module parse failed: Unexpected token (56:57)
File was processed with these loaders:
> * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   }
|
>   const theme = props.color ? undefined : DEFAULT_THEME ?? props.theme;
|   const labels = {
|     totalCount: `{{count}} contributions in ${year === 'last' ? 'the last year' : '{{year}}'}`

**Comment by grubersjoe** [comment]
Ah, crap. Sorry, I forgot that `create-react-app`  does not support the nullish coalescing operator. Fixed in `v3.0.5`. I also tested in this time in `create-react-app` :sweat_smile: .

**Comment by Newgin-sam** [comment]
thanks for your time joe its working fine now .

**Comment by 1chooo** [comment]
Hi @grubersjoe 

The original personal webpage used an older version. Now, it has been updated to `"react-github-calendar": "^4.1.1"`. However, it was noticed that the color attribute is no longer functional. If there's a desire to update the color, could you please provide guidance on how to achieve this with the current methods?

Below is the previous method used to change the color:

```jsx
<GitHubCalendar
    username="1chooo"
    blockSize={15}
    blockMargin={5}
    color="#E7BB5E"
    fontSize={16}
/>
```

Thanks for your helping!
