### ISSUE TITLE
Allow user to specify which url to fetch

### ISSUE THREAD

**Issue by nicosh** [grubersjoe/react-github-calendar#30]
Since third parties endpoints are subject to issues, would be nice to give the user the option to chose where fetch the data.
For example, with next.js (or a custom express server) is really simple to use the official apis without expose any personal token.

Example : 
```
import GitHubCalendar from 'react-github-calendar';

<GitHubCalendar endpoint="/get-contributions" username="grubersjoe" /> 
```

If you want i can submit a PR

**Comment by grubersjoe** [comment]
Hey. I'm not convinced that this property is really necessary. This component is only a thin wrapper around [`react-activity-calendar`](https://github.com/grubersjoe/react-activity-calendar) (check out the [code](https://github.com/grubersjoe/react-github-calendar/blob/master/src/index.tsx)). So if you want to use another API to fetch contributions data you can easily achieve this by passing this data directly to `<ActivityCalendar />`:

```ts
import ActivityCalendar from 'react-activity-calendar';

const data = await (await fetch(someApi)).json();

// ...

<ActivityCalendar data={data} />
```

Would this fulfill your requirement?

**Comment by nicosh** [comment]
@grubersjoe  Yes, you are definitely right, at the time of writing i was not aware of `react-activity-calendar`, and i ended using that.
