### ISSUE TITLE
Design breaks slightly when using with Chakra UI

### ISSUE THREAD

**Issue by ownchoice** [grubersjoe/react-github-calendar#35]
The "less - more" div stacks vertically instead of horizontally.

![image](https://user-images.githubusercontent.com/22414323/144147441-3d79dfe5-d509-4902-ad07-3162b1bba79c.png)

It happens when using with [Chakra UI](https://chakra-ui.com/).

- [Codesandbox's example](https://codesandbox.io/s/react-chakra-ui-react-github-calendar-9zv9z?file=/src/App.js)
- [Stackblitz's example](https://stackblitz.com/edit/react-j1wbyx?file=src/App.js)

**Comment by grubersjoe** [comment]
Hey. This stems from Chakra adding a global style that sets the following:

```css
svg {
  display: block;
}
```

I've updated the component to handle this. Should be fixed with v3.2.2.

**Comment by ownchoice** [comment]
Thank you, that fixed it!
