### ISSUE TITLE
Color scheme issue

### ISSUE THREAD

**Issue by raaahad** [grubersjoe/react-github-calendar#38]
github color scheme is not matching right way in dark mode app. It has just shifted.

**Comment by grubersjoe** [comment]
Hey. I'm currently looking into this, maybe CSS variables are an approach here. But I can't promise it'll work out.

**Comment by BrianRuizy** [comment]
> 

were you able to figure a dark mode?

**Comment by grubersjoe** [comment]
> @grubersjoe 
> 
> were you able to figure a dark mode?

Hey. I started working on it some months ago, but then other things got in the way. I'll come back to this soon.

**Comment by BrianRuizy** [comment]
Seems straightforward, probably set a boolean _dark_ parameter.
Here are the values I'm using mocking GitHub dark colors

```js
{
    "level4": '#39d353',
    "level3": '#26a641',
    "level2": '#006d32',
    "level1": '#0e4429',
    "level0": '#262626',
}
```

**Comment by grubersjoe** [comment]
Dark mode is supported now with v4.
