### ISSUE TITLE
Issue rendering the Calendar

### ISSUE THREAD

**Issue by adityamulik** [grubersjoe/react-github-calendar#41]
Hello,
My portfolio website's GitHub Calendar is not rendering. 
https://www.adityamulik.com/

Below are the versions of React & react-github-calendar
"react": "^17.0.2",
"react-github-calendar": "^2.0.2"

**Comment by grubersjoe** [comment]
Hey. Please update to v3. 

v2 uses an older version of the API to fetch the GitHub contribution data that was deployed on Heroku. Since Heroku decided to ditch their free plans this old API no longer works:

https://help.heroku.com/RSBRUH58/removal-of-heroku-free-product-plans-faq

**Comment by adityamulik** [comment]
@grubersjoe Much thanks for the update :)
