### ISSUE TITLE
Global CSS cannot be imported from within node_modules

### ISSUE THREAD

**Issue by maurana** [grubersjoe/react-github-calendar#45]
./node_modules/react-github-calender/lib/GithubCalender.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules\react-github-calender\lib\GithubCalender.js

- Typescript
- Next Js v13.1.6
- React v18.2.0
- react-github-calender v1.1.0

**Comment by grubersjoe** [comment]
Hey. Are you sure about the version? `v1.1.0` does not exist ([see here](https://www.npmjs.com/package/react-github-calendar?activeTab=versions)). In any case, please update to the latest version `v3.4.0` and try again.

I've created a new Next.js project and tried to reproduce this error, but the calendar rendered just fine. Please provide an example repository to reproduce if this error persists.
