### ISSUE TITLE
Ability to display a custom error message

### ISSUE THREAD

**Issue by marcelscruz** [grubersjoe/react-github-calendar#65]
I couldn't find any way to catch an error while loading the graph (e.g. the username isn't valid) and then show a custom error message.
Is this possible, or is it a planned feature?
Thanks!

**Comment by grubersjoe** [comment]
Hey. Good idea, the current approach was not very well thought out. The component will simply throw now as of v4.1.0, so error boundaries can be used now.

https://github.com/grubersjoe/react-github-calendar/releases/tag/v4.1

**Comment by marcelscruz** [comment]
Btw, this is my current hack, if anyone else needs it.

<img width="687" alt="Screenshot 2024-01-16 at 23 34 45" src="https://github.com/grubersjoe/react-github-calendar/assets/12413903/82356963-8623-4ae6-881b-7e24b60b47e0">

**Comment by grubersjoe** [comment]
Agreed, would be a nice addition. Also it would be a breaking change if the component all of a sudden throws when it did not before on error. So I added the `throwOnError` and `errorMessage` props and `throwOnError` is `false` by default. Thanks for the good feedback 👍.

Released in v4.1.1.

**Comment by marcelscruz** [comment]
Amazing, thanks for looking after it!
