### ISSUE TITLE
Github Calendar Component not updating when username is dynamically changed

### ISSUE THREAD

**Issue by CoreyGumbs** [grubersjoe/react-github-calendar#7]
I am using react-github-calendar with the github api. I created an app that allows for searching github user profile data. 

 my site: [https://react-github-usercard-corey-gumbs.netlify.com/](url)

when I search for a user and dynamically update the username, when the page renders with their profile  data of user that was searched for, it doesn't trigger the calendar component to update and re-render the new user's contribution data.

It shows original user contribution data which persists no matter what user(s) you search for.

**Comment by grubersjoe** [comment]
Hey. My bad, the component did not perform another API request if the username prop has changed. It's fixed now in v0.15.3. Please give it another try.

I've also added an input on the demo page to try this: 
https://grubersjoe.github.io/react-github-calendar/

**Comment by CoreyGumbs** [comment]
Ok thank you.  I will try your recommendation

**Comment by CoreyGumbs** [comment]
> Hey. My bad, the component did not perform another API request if the username prop has changed. It's fixed now in v0.15.3. Please give it another try.
> 
> I've also added an input on the demo page to try this:
> https://grubersjoe.github.io/react-github-calendar/
> 
> Edit: I've seen in your code, that you update the username onChange of the input field. You might want to wait for a button click, because every key stroke will trigger another API request otherwise.

**Comment by mphelps1978** [comment]
I was running into a simmilar issue as Corey. Once I updated the package, I am starting to get this: 

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

code is at 

https://github.com/mphelps1978/React-Github-User-Card/blob/Michael-Phelps-CalendarIssue/github-user-card/src/components/MyProfile.js  if you want to take a peek.

**Comment by CoreyGumbs** [comment]
Im getting the same error as @mphelps1978 

```Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.```

```Check the render method of App.```

**Comment by agohorel** [comment]
I had the previous version working but am now encountering this error as well. @CoreyGumbs if you have any thoughts on how to resolve this I would be glad to take a stab at opening a PR. Appreciate your work on this!

**Comment by grubersjoe** [comment]
I've updated this package to CRA v3 some time ago. Unfortunately, the Webpack config seems to be broken right now. I'll look into this the next days to fix it asap. Sorry for breaking it :sweat_smile: ...

**Comment by grubersjoe** [comment]
Please give it another try. It should no longer crash in `0.16.0` and work correctly. I switched to Rollup to bundle the package now. Also I've tested it with CRA: importing and using the calendar worked.

**Comment by CoreyGumbs** [comment]
@grubersjoe  Its working. Everything is working fine! I will close this issue. Thank you!
