### ISSUE TITLE
Error Fetching GitHub contribution data for "..." failed: User "..." not found.

### ISSUE THREAD

**Issue by adriangalilea** [grubersjoe/react-github-calendar#82]
Hello,

I've implemented your component in a site I'm developing,

[e-id.to/adriangalilea](https://e-id.to/adriangalilea)

After a while I get
```
Error Fetching GitHub contribution data for "..." failed: User "..." not found.
```
I'm guessing this is due being rate limited, If this is the case a clear error message for rate limiting would be nice.

As you can see it happens to me even on your site:
<img width="738" alt="image" src="https://github.com/grubersjoe/react-github-calendar/assets/90320947/9ff78232-241a-43c0-9f41-362613b14056">

I've also noticed this:
```
A simple API that returns number of GitHub contributions based on a users GitHub profile. This API is used by [React GitHub Calendar](https://github.com/grubersjoe/react-github-calendar) (React component).

⚠️ Results are cached for one hour!
```

So it's not clear to me why this could be the case, maybe it's how I'm using it on dev that's not caching it appropriately.

[This is the file](https://github.com/adriangalilea/e-id/blob/main/components/social_component/github_activity.tsx) and my next.js project.

How can I debug the caching?

I would also like to customise for how long or where I store the data preferably, is this reasonable?

Or perhaps your other 2 libraries in conjunction would lead me to have more manual control over this?

Thank you for this great component,

Adrian.

**Comment by grubersjoe** [comment]
Hey. Thanks for reporting this! However, caching is not the issue, but GitHub seems to have changed how the contribution graph is rendered. Now client-side JavaScript appears to be required. Consequently, the contribution information can no longer be retrieved by looking at the prerendered HTML source.

So this will make things a lot harder, unfortunately, and I have to think about this.

**Comment by adriangalilea** [comment]
> Hey. Thanks for reporting this! However, caching is not the issue, but GitHub seems to have changed how the contribution graph is rendered. Now client-side JavaScript appears to be required. You can test this by disabling JavaScript in your browser (the chart never shows up, but you will only see a spinner forever). Consequently, the contribution data can no longer be scraped by simply parsing the HTML source.
> 
> So this will make this a lot harder, unfortunately, and I have to think about this. There probably is no way around something like Puppeteer which sounds quite heavy.

Oh wow, I thought this was using API or something.

Regarding client-side, I do force the component to run client side `"use client";` but still fails, was working great yesterday.

**Comment by grubersjoe** [comment]
This component does use an API that does the scraping:
https://github.com/grubersjoe/github-contributions-api

The described issue is in the context of this API.

**Comment by adriangalilea** [comment]
> This component does use an API that handles the scraping: https://github.com/grubersjoe/github-contributions-api
> 
> The described issue is in the context of this API.

What about using something like [this](https://microlink.io/recipes/github) it's freemium, but perhaps alongside a good caching strategy can go a long way.

**Comment by grubersjoe** [comment]
Puppeteer is not hard to use and Microlink [seems to use it under the hood](https://microlink.io/oss) as well. So I guess I'll have to move [github-contributions-api](https://github.com/grubersjoe/github-contributions-api) from Cheerio to Puppeteer. This will take a bit of time, though. Sorry people.

**Comment by shinobi8894** [comment]
So, we can't get contrbution of github anymore ?

**Comment by grubersjoe** [comment]
Yes, not until the API is fixed, which I'll do as soon a possible.

The issue with scraping simply is that it can break any time when GitHub changes how they render the calendar.

**Comment by PrarthnaLuthra** [comment]
> Hi roughly how much time will it take for this issue to be fixed?

**Comment by PrarthnaLuthra** [comment]
It would be really helpful if it gets fixed early

**Comment by PrarthnaLuthra** [comment]
Sure thanks!

**Comment by tommypurcell** [comment]
Thanks for posting this issue! 

Is the problem that the github API does not serve the contribution data so it needs to be scraped? 

I understand from your messages that Github changed their calendar rendering which broke react-github-calendar.

**Comment by PrarthnaLuthra** [comment]
I tried to fetch this endpoint https://api.github.com/users/${username}/contributions but I am getting this error {
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest"
}

**Comment by tommypurcell** [comment]
Yea I'm not seeing that as an endpoint.

**Comment by adriangalilea** [comment]
@ everyone

Don't pressure grubersjoe we should just be thankful and patient or try to fix it ourselves since it's opensource.

Keep the conversation clean and read the messages above before commenting, remember that everyone subscribed to this thread will get emails and notifications.

**Comment by jiwooproity** [comment]
Thanks for posting this issue.
I'm using your api really well. I'll be rooting for you.

**Comment by paulaneesh7** [comment]
> I'll be working on it this weekend. A few days at most.
> 
> Please see this issue for further progress: [grubersjoe/github-contributions-api#7](https://github.com/grubersjoe/github-contributions-api/issues/7)

I had this contribution graph embedded in my site and suddenly I saw error in fetching the data, thanks for this info that it will fixed

**Comment by sampconrad** [comment]
Appreciate you being on top of this so quickly @grubersjoe . Godspeed to ya!

You're the man!

**Comment by grubersjoe** [comment]
@d3or found a nice and easy solution: https://github.com/grubersjoe/github-contributions-api/pull/8

Just deployed the latest version of the API, everything should work again!

**Comment by PrarthnaLuthra** [comment]
> @d3or found a nice and easy solution: [grubersjoe/github-contributions-api#8](https://github.com/grubersjoe/github-contributions-api/pull/8)
> 
> Just deployed the latest version of the API, everything should work again!

Thank you so much!
