### ISSUE TITLE
Separate UI and  github

### ISSUE THREAD

**Issue by KhalilMohammad** [grubersjoe/react-github-calendar#9]
I recommend that you create another project.

Current project should focus only on react GitHub calendar while other project can act as base ui.
All GitHub data is passing through props.

It would be useful for me as other other
I could the ui component to show attendance throughout the year month days.

**Comment by grubersjoe** [comment]
Sorry, but I don't really understand what you mean. This component fetches the contribution data from an API ([code is here](https://github.com/grubersjoe/github-contributions-api)) and renders the calendar. What do you mean with "base ui"? That the calendar should be broken down into several individual components, which can be used standalone?

**Comment by KhalilMohammad** [comment]
I have already copied code for my usage.

Basically. I was saying that you are saying github services directly into ui component.
It would be better if you just pass github data as props.

That would make it easier for anyone who want to pass some other data instead of github data.
