### ISSUE TITLE
Getting an failed to resolve error 

### ISSUE THREAD

**Issue by rk301999** [grubersjoe/react-github-calendar#94]
![image](https://github.com/grubersjoe/react-github-calendar/assets/42288787/1a3b2c46-f4b2-466a-97bc-85b96e8ce63e)

**Comment by grubersjoe** [comment]
Hey. Can you share the repo or provide some reproduction? Without any context it's impossible to say what's wrong.

**Comment by grubersjoe** [comment]
Closing since now answer.
